export interface Station {
  id: number
  name: string
  address: string
  latitude: number
  longitude: number
  fuel_types: string[]
  price: number
  rating?: number
  distance?: string
  googleMapsUrl?: string
}

export interface GasStation {
  id: number
  name: { uz: string; en: string; ru: string }
  address: { uz: string; en: string; ru: string }
  lat: number
  lng: number
  fuel_types: string[]
  prices: { [key: string]: number }
  rating: number
}

export const mockStations: Station[] = [
  {
    id: 1,
    name: "Chinobod oil",
    address: "Urgench, Xorazm Region",
    latitude: 41.55,
    longitude: 60.625,
    fuel_types: ["AI-92", "AI-95", "Dizel"],
    price: 10200,
    rating: 4.5,
    googleMapsUrl: "https://maps.app.goo.gl/uKdnTPHHgK2Ji2g47",
  },
  {
    id: 2,
    name: "Metan gaz",
    address: "GJHF+9X, Urgench, Xorazm Region",
    latitude: 41.5283,
    longitude: 60.6247,
    fuel_types: ["Metan"],
    price: 5500,
    rating: 3.7,
    googleMapsUrl: "https://maps.app.goo.gl/P4fWuoeneNRXYvNp6",
  },
  {
    id: 3,
    name: "Metan Toshbozor",
    address: "JH3R+WW, Urgench, Xorazm Region",
    latitude: 41.5547,
    longitude: 60.6422,
    fuel_types: ["Metan"],
    price: 5500,
    rating: 4.5,
    googleMapsUrl: "https://maps.app.goo.gl/aZ9cDs8gsJ8tZJ3S9",
  },
  {
    id: 4,
    name: "Inoyat invest",
    address: "GHGJ+9G6, Хива йули, Urgench",
    latitude: 41.4758,
    longitude: 60.6311,
    fuel_types: ["Dizel"],
    price: 11000,
    rating: 5.0,
    googleMapsUrl: "https://maps.app.goo.gl/TxMfB7fJX6h8xTWw7",
  },
  {
    id: 5,
    name: "MMS Metan Zapravka",
    address: "R-159, Urgench",
    latitude: 41.5442,
    longitude: 60.6492,
    fuel_types: ["Metan", "Dizel"],
    price: 5500,
    rating: 4.6,
    googleMapsUrl: "https://maps.app.goo.gl/83giZAT8uVK4gjMq9",
  },
  {
    id: 6,
    name: "Turon Oil Petrol Station",
    address: "A-380, Urganch, Xorazm",
    latitude: 41.55063,
    longitude: 60.63144,
    fuel_types: ["AI-92", "AI-95", "Dizel"],
    price: 10200,
    rating: 4.7,
    googleMapsUrl: "https://maps.app.goo.gl/Ti6sHTQ46PkzJRUt9",
  },
  {
    id: 7,
    name: "O'ZNEFTMAHSULOT AJ Urganch AZS №55",
    address: "Al-Xorazmiy ko'chasi, Urganch",
    latitude: 41.55425,
    longitude: 60.62489,
    fuel_types: ["AI-80", "AI-92", "AI-95", "Dizel"],
    price: 10100,
    rating: 4.5,
    googleMapsUrl: "https://maps.app.goo.gl/GbL7v7HXSuMAp6aY6",
  },
  {
    id: 8,
    name: "AZS Xiva",
    address: "Yangi Xiva yo'li, Xiva",
    latitude: 41.38883,
    longitude: 60.35953,
    fuel_types: ["AI-92", "AI-95", "Dizel"],
    price: 10300,
    rating: 4.6,
    googleMapsUrl: "https://maps.app.goo.gl/2zV3mMDMFnPC26eL6",
  },
  {
    id: 9,
    name: "AZS №32",
    address: "Toshkent yo'li, Urganch",
    latitude: 41.54389,
    longitude: 60.61156,
    fuel_types: ["AI-92", "Dizel"],
    price: 10150,
    rating: 4.4,
    googleMapsUrl: "https://maps.app.goo.gl/n2hfcb86RWwj1xHX8",
  },
  {
    id: 10,
    name: "O'ZNEFTMAHSULOT Xiva",
    address: "Al-Xorazmiy ko'chasi, Xiva",
    latitude: 41.37856,
    longitude: 60.36289,
    fuel_types: ["AI-80", "AI-92", "AI-95", "Dizel"],
    price: 10250,
    rating: 4.8,
    googleMapsUrl: "https://maps.app.goo.gl/bhTE2AWcPt9FFFv67",
  },
  {
    id: 11,
    name: "Turon Oil - Gurlan",
    address: "Mustaqillik ko'chasi, Gurlan",
    latitude: 41.84532,
    longitude: 60.38545,
    fuel_types: ["AI-92", "Dizel"],
    price: 10100,
    rating: 4.3,
    googleMapsUrl: "https://maps.app.goo.gl/VGim68dnNeNSBAeo7",
  },
  {
    id: 12,
    name: "AZS Urganch Markaz",
    address: "Navoi ko'chasi, Urganch",
    latitude: 41.55127,
    longitude: 60.63518,
    fuel_types: ["AI-92", "AI-95", "Dizel"],
    price: 10180,
    rating: 4.6,
    googleMapsUrl: "https://maps.app.goo.gl/rZ9tYobN9zc5U8GQ6",
  },
  {
    id: 13,
    name: "Benzin Quyish Shoxobchasi - Hazorasp",
    address: "Amir Temur ko'chasi, Hazorasp",
    latitude: 41.32345,
    longitude: 61.06784,
    fuel_types: ["AI-80", "AI-92", "Dizel"],
    price: 10150,
    rating: 4.4,
    googleMapsUrl: "https://maps.app.goo.gl/XjVysvuUhqwyT1Sn9",
  },
  {
    id: 14,
    name: "AZS Xonqa",
    address: "Yangibozor yo'li, Xonqa",
    latitude: 41.72345,
    longitude: 60.88543,
    fuel_types: ["AI-92", "AI-95"],
    price: 10200,
    rating: 4.5,
    googleMapsUrl: "https://maps.app.goo.gl/fRyor1afPdRhhCM3A",
  },
  {
    id: 15,
    name: "Benzin Quyish - Bog'ot",
    address: "Toshkent yo'li, Bog'ot",
    latitude: 41.53453,
    longitude: 60.95674,
    fuel_types: ["AI-92", "Dizel"],
    price: 10100,
    rating: 4.3,
    googleMapsUrl: "https://maps.app.goo.gl/qbmAY81chmZg8mWg9",
  },
  {
    id: 16,
    name: "Turon Oil - Shovot",
    address: "Dustlik ko'chasi, Shovot",
    latitude: 41.62345,
    longitude: 60.31456,
    fuel_types: ["AI-92", "Dizel"],
    price: 10150,
    rating: 4.4,
    googleMapsUrl: "https://maps.app.goo.gl/1MgSmMgry2ARkA9m6",
  },
  {
    id: 17,
    name: "AZS Qo'shko'pir",
    address: "Buxoro yo'li, Qo'shko'pir",
    latitude: 41.53125,
    longitude: 60.34567,
    fuel_types: ["AI-92", "Dizel"],
    price: 10180,
    rating: 4.2,
    googleMapsUrl: "https://maps.app.goo.gl/PVmnnYgraJTgwvLEA",
  },
  {
    id: 18,
    name: "Azs",
    address: "GJQ8+4QW, Urgench, Xorazm Region",
    latitude: 41.538,
    longitude: 60.617,
    fuel_types: ["AI-92", "Dizel"],
    price: 10150,
    rating: 5.0,
    googleMapsUrl: "https://maps.app.goo.gl/3c3DeTTaL22DZpnc6",
  },
  {
    id: 19,
    name: "Azs Benzin",
    address: "Urgench, Xorazm Region",
    latitude: 41.545,
    longitude: 60.628,
    fuel_types: ["AI-80", "AI-92"],
    price: 10100,
    rating: 4.0,
    googleMapsUrl: "https://maps.app.goo.gl/9NYzxUbNnhNmX56s6",
  },
  {
    id: 20,
    name: "Zapravka",
    address: "Urgench, Xorazm Region",
    latitude: 41.548,
    longitude: 60.635,
    fuel_types: ["AI-92", "AI-95", "Dizel"],
    price: 10200,
    rating: 5.0,
    googleMapsUrl: "https://maps.app.goo.gl/hVQVPcAe7XuiDY2v5",
  },
  {
    id: 21,
    name: "Metan Zapravka",
    address: "Urgench, Xorazm Region",
    latitude: 41.552,
    longitude: 60.642,
    fuel_types: ["Metan"],
    price: 5500,
    rating: 4.5,
    googleMapsUrl: "https://maps.app.goo.gl/KinG16spWZY3898v5",
  },
  {
    id: 22,
    name: "AZS №41",
    address: "Urgench, Xorazm Region",
    latitude: 41.556,
    longitude: 60.638,
    fuel_types: ["AI-92", "AI-95", "Dizel"],
    price: 10180,
    rating: 4.3,
    googleMapsUrl: "https://maps.app.goo.gl/LkvGZTVM4YFg5Wyt7",
  },
  {
    id: 23,
    name: "Propan Zapravka",
    address: "Urgench, Xorazm Region",
    latitude: 41.549,
    longitude: 60.629,
    fuel_types: ["Propan"],
    price: 6000,
    rating: 4.2,
    googleMapsUrl: "https://maps.app.goo.gl/BkKXjbef89eipYox5",
  },
  {
    id: 24,
    name: "Yoqilg'i Shoxobchasi",
    address: "Urgench, Xorazm Region",
    latitude: 41.543,
    longitude: 60.621,
    fuel_types: ["AI-92", "Dizel"],
    price: 10150,
    rating: 4.4,
    googleMapsUrl: "https://maps.app.goo.gl/3P4STYYnB6uAPoS1A",
  },
  {
    id: 25,
    name: "Benzin AZS",
    address: "Urgench, Xorazm Region",
    latitude: 41.558,
    longitude: 60.644,
    fuel_types: ["AI-80", "AI-92", "AI-95"],
    price: 10200,
    rating: 4.6,
    googleMapsUrl: "https://maps.app.goo.gl/tWfAB43DcaDMNwWM6",
  },
  {
    id: 26,
    name: "Dizel Zapravka",
    address: "Urgench, Xorazm Region",
    latitude: 41.541,
    longitude: 60.633,
    fuel_types: ["Dizel"],
    price: 11000,
    rating: 4.1,
    googleMapsUrl: "https://maps.app.goo.gl/rpn7uuPxZDDwUABq7",
  },
  {
    id: 27,
    name: "AZS Urganch Sharq",
    address: "Urgench, Xorazm Region",
    latitude: 41.554,
    longitude: 60.648,
    fuel_types: ["AI-92", "AI-95", "Dizel"],
    price: 10180,
    rating: 4.5,
    googleMapsUrl: "https://maps.app.goo.gl/pNvNtcm8v1oHg3FSA",
  },
  {
    id: 28,
    name: "Metan Sharq",
    address: "Urgench, Xorazm Region",
    latitude: 41.557,
    longitude: 60.651,
    fuel_types: ["Metan"],
    price: 5500,
    rating: 4.3,
    googleMapsUrl: "https://maps.app.goo.gl/RpTAsqwRW4eN2Ru68",
  },
  {
    id: 29,
    name: "Benzin №22",
    address: "Urgench, Xorazm Region",
    latitude: 41.546,
    longitude: 60.626,
    fuel_types: ["AI-92", "Dizel"],
    price: 10150,
    rating: 4.4,
    googleMapsUrl: "https://maps.app.goo.gl/hsXr6iKG2NSfp2Ga6",
  },
  {
    id: 30,
    name: "AZS Centrum",
    address: "Urgench, Xorazm Region",
    latitude: 41.551,
    longitude: 60.636,
    fuel_types: ["AI-80", "AI-92", "AI-95", "Dizel"],
    price: 10200,
    rating: 4.7,
    googleMapsUrl: "https://maps.app.goo.gl/Qju7BrKN4S6o7YY66",
  },
  {
    id: 31,
    name: "Yoqilg'i AZS",
    address: "Urgench, Xorazm Region",
    latitude: 41.544,
    longitude: 60.619,
    fuel_types: ["AI-92", "AI-95"],
    price: 10180,
    rating: 4.2,
    googleMapsUrl: "https://maps.app.goo.gl/VvrcZuUqHc75JaKH9",
  },
  {
    id: 32,
    name: "Benzin Quyish Markazi",
    address: "Urgench, Xorazm Region",
    latitude: 41.553,
    longitude: 60.64,
    fuel_types: ["AI-92", "Dizel"],
    price: 10150,
    rating: 4.5,
    googleMapsUrl: "https://maps.app.goo.gl/GgvkzbVAJhT7A3nu9",
  },
  {
    id: 33,
    name: "Propan-Metan Kompleks",
    address: "Urgench, Xorazm Region",
    latitude: 41.547,
    longitude: 60.631,
    fuel_types: ["Propan", "Metan"],
    price: 5800,
    rating: 4.4,
    googleMapsUrl: "https://maps.app.goo.gl/BhvxcCjerkxwCREs8",
  },
  {
    id: 34,
    name: "AZS Express",
    address: "Urgench, Xorazm Region",
    latitude: 41.559,
    longitude: 60.646,
    fuel_types: ["AI-92", "AI-95", "Dizel"],
    price: 10200,
    rating: 4.6,
    googleMapsUrl: "https://maps.app.goo.gl/R6qmY6fPEMPBQrhX6",
  },
  {
    id: 35,
    name: "Yoqilg'i №15",
    address: "Urgench, Xorazm Region",
    latitude: 41.542,
    longitude: 60.623,
    fuel_types: ["AI-92", "Dizel"],
    price: 10150,
    rating: 4.3,
    googleMapsUrl: "https://maps.app.goo.gl/45C8fRDcyde3pD6R7",
  },
  {
    id: 36,
    name: "Benzin Station",
    address: "Urgench, Xorazm Region",
    latitude: 41.555,
    longitude: 60.643,
    fuel_types: ["AI-80", "AI-92", "AI-95"],
    price: 10180,
    rating: 4.5,
    googleMapsUrl: "https://maps.app.goo.gl/AQPRJBVrxz7YGPM77",
  },
  {
    id: 37,
    name: "AZS Yulduz",
    address: "Urgench, Xorazm Region",
    latitude: 41.56,
    longitude: 60.649,
    fuel_types: ["AI-92", "AI-95", "Dizel"],
    price: 10200,
    rating: 4.7,
    googleMapsUrl: "https://maps.app.goo.gl/o8rykk8AfdCmYovZ6",
  },
]

export function calculateDistance(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371 // Earth's radius in km
  const dLat = ((lat2 - lat1) * Math.PI) / 180
  const dLon = ((lon2 - lon1) * Math.PI) / 180
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) * Math.cos((lat2 * Math.PI) / 180) * Math.sin(dLon / 2) * Math.sin(dLon / 2)
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))
  return R * c
}

export function getGasStations(): GasStation[] {
  // Convert mockStations to GasStation format
  return mockStations.map((station) => ({
    id: station.id,
    name: { uz: station.name, en: station.name, ru: station.name },
    address: { uz: station.address, en: station.address, ru: station.address },
    lat: station.latitude,
    lng: station.longitude,
    fuel_types: station.fuel_types,
    prices: station.fuel_types.reduce((acc, type) => ({ ...acc, [type]: station.price }), {}),
    rating: station.rating || 4.0,
  }))
}
